# Generated by Django 4.2.7 on 2023-11-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_deluxeroom_familyroom_standardroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.IntegerField(choices=[(1, 'Standard Rooms'), (2, 'Deluxe Rooms'), (3, 'Family Rooms')], default=1),
        ),
    ]
