# Generated by Django 4.2.7 on 2023-11-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenity',
            new_name='Amenities',
        ),
    ]
