# Generated by Django 4.2.7 on 2023-11-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_amenity_amenities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenities',
            new_name='Amenitie',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='amenities',
            new_name='amenitie',
        ),
    ]
